const recipe = [
  {
  "id": 716426,
  "name": "Cauliflower, Brown Rice, and Vegetable Fried Rice",
  "image": "https://spoonacular.com/recipeImages/716426-312x231.jpg",
  "imageType": "jpg",
  "readyInMinutes": 45,
  "servings": 2,
  "vegan": false,
  "vegetarian": false,
  "dairy_free": false,
  "gluten_free": false,
  "keto": false,
  "low_fodmap": false,
  "ingredients": [
    "2 tablespoons canola oil or vegetable oil, divided",
    "4 scallions, chopped",
    "1 ½ cups frozen peas and carrots",
    "1 (10-oz.) package frozen riced cauliflower",
    "1 cup frozen cooked brown rice",
    "½ teaspoon ground ginger",
    "½ teaspoon garlic powder",
    "2 large eggs, lightly beaten",
    "1 tablespoon reduced-sodium soy sauce"
  ],
  "instructions":['Heat 1 Tbsp. oil in a large nonstick skillet over medium-high heat.',
  'Add scallions; stir-fry until softened, 3 to 5 minutes.',
  'Add peas and carrots; cook, stirring, for 1 minute. Stir in cauliflower.',
  'Continue stir-frying just until the vegetables are barely softened and the pan is mostly dry, 5 to 7 minutes.',
  'Add the remaining 1 Tbsp. oil, rice, ginger, and garlic powder; stir to coat well.',
  'Cook, stirring, until the mixture is heated through, 3 to 4 minutes.',
  'Push the rice-vegetable mixture to the sides of the pan and pour in eggs, stirring to scramble them until just set, then fold the eggs into the rest of the mixture.',
  'Stir in soy sauce and serve immediately.'],
  "summary": "Pasta with Garlic, Scallions, Cauliflower & Breadcrumbs might be a good recipe to expand your main course repertoire. One portion of this dish contains approximately <b>19g of protein </b>,  <b>20g of fat </b>, and a total of  <b>584 calories </b>. For  <b>$1.63 per serving </b>, this recipe  <b>covers 23% </b> of your daily requirements of vitamins and minerals. This recipe serves 2. It is brought to you by fullbellysisters.blogspot.com. 209 people were glad they tried this recipe. A mixture of scallions, salt and pepper, white wine, and a handful of other ingredients are all it takes to make this recipe so scrumptious. From preparation to the plate, this recipe takes approximately  <b>45 minutes </b>. All things considered, we decided this recipe  <b>deserves a spoonacular score of 83% </b>. This score is awesome. If you like this recipe, take a look at these similar recipes: <a href=\"https://spoonacular.com/recipes/cauliflower-gratin-with-garlic-breadcrumbs-318375\">Cauliflower Gratin with Garlic Breadcrumbs</a>, < href=\"https://spoonacular.com/recipes/pasta-with-cauliflower-sausage-breadcrumbs-30437\">Pasta With Cauliflower, Sausage, & Breadcrumbs</a>, and <a href=\"https://spoonacular.com/recipes/pasta-with-roasted-cauliflower-parsley-and-breadcrumbs-30738\">Pasta With Roasted Cauliflower, Parsley, And Breadcrumbs</a>.",
  "calories": 700,
  "protien": 300,
  "fat": 100,
  "carbs": 300,
  "popularity_score": 17,
  "likes": 25
},
{
  "id": 715594,
  "name": "Homemade Garlic and Basil French Fries",
  "image": "https://spoonacular.com/recipeImages/715594-312x231.jpg",
  "imageType": "jpg",
        "readyInMinutes": 45,
  "servings": 2,
  "vegan": false,
  "vegetarian": false,
  "dairy_free": false,
  "gluten_free": false,
  "keto": false,
  "low_fodmap": false,
  "ingredients": [
    "2 tablespoons canola oil or vegetable oil, divided",
    "4 scallions, chopped",
    "1 ½ cups frozen peas and carrots",
    "1 (10-oz.) package frozen riced cauliflower",
    "1 cup frozen cooked brown rice",
    "½ teaspoon ground ginger",
    "½ teaspoon garlic powder",
    "2 large eggs, lightly beaten",
    "1 tablespoon reduced-sodium soy sauce"
  ],
  "instructions": ['Heat 1 Tbsp. oil in a large nonstick skillet over medium-high heat.',
  'Add scallions; stir-fry until softened, 3 to 5 minutes.',
  'Add peas and carrots; cook, stirring, for 1 minute. Stir in cauliflower.',
  'Continue stir-frying just until the vegetables are barely softened and the pan is mostly dry, 5 to 7 minutes.',
  'Add the remaining 1 Tbsp. oil, rice, ginger, and garlic powder; stir to coat well.',
  'Cook, stirring, until the mixture is heated through, 3 to 4 minutes.',
  'Push the rice-vegetable mixture to the sides of the pan and pour in eggs, stirring to scramble them until just set, then fold the eggs into the rest of the mixture.',
  'Stir in soy sauce and serve immediately.'],
  "summary": "Pasta with Garlic, Scallions, Cauliflower & Breadcrumbs might be a good recipe to expand your main course repertoire. One portion of this dish contains approximately <b>19g of protein </b>,  <b>20g of fat </b>, and a total of  <b>584 calories </b>. For  <b>$1.63 per serving </b>, this recipe  <b>covers 23% </b> of your daily requirements of vitamins and minerals. This recipe serves 2. It is brought to you by fullbellysisters.blogspot.com. 209 people were glad they tried this recipe. A mixture of scallions, salt and pepper, white wine, and a handful of other ingredients are all it takes to make this recipe so scrumptious. From preparation to the plate, this recipe takes approximately  <b>45 minutes </b>. All things considered, we decided this recipe  <b>deserves a spoonacular score of 83% </b>. This score is awesome. If you like this recipe, take a look at these similar recipes: <a href=\"https://spoonacular.com/recipes/cauliflower-gratin-with-garlic-breadcrumbs-318375\">Cauliflower Gratin with Garlic Breadcrumbs</a>, < href=\"https://spoonacular.com/recipes/pasta-with-cauliflower-sausage-breadcrumbs-30437\">Pasta With Cauliflower, Sausage, & Breadcrumbs</a>, and <a href=\"https://spoonacular.com/recipes/pasta-with-roasted-cauliflower-parsley-and-breadcrumbs-30738\">Pasta With Roasted Cauliflower, Parsley, And Breadcrumbs</a>.",
  "calories": 700,
  "protein": 300,
  "fat": 100,
  "carbs": 300,
  "popularity_score": 17,
  "likes": 25
},
{
  "id": 715497,
  "name": "Berry Banana Breakfast Smoothie",
  "image": "https://spoonacular.com/recipeImages/715497-312x231.jpg",
  "imageType": "jpg",
        "readyInMinutes": 45,
  "servings": 2,
  "vegan": false,
  "vegetarian": false,
  "dairy_free": false,
  "gluten_free": false,
  "keto": false,
  "low_fodmap": false,
  "ingredients": [
    "2 tablespoons canola oil or vegetable oil, divided",
    "4 scallions, chopped",
    "1 ½ cups frozen peas and carrots",
    "1 (10-oz.) package frozen riced cauliflower",
    "1 cup frozen cooked brown rice",
    "½ teaspoon ground ginger",
    "½ teaspoon garlic powder",
    "2 large eggs, lightly beaten",
    "1 tablespoon reduced-sodium soy sauce"
  ],
  "instructions": ['Heat 1 Tbsp. oil in a large nonstick skillet over medium-high heat.',
  'Add scallions; stir-fry until softened, 3 to 5 minutes.',
  'Add peas and carrots; cook, stirring, for 1 minute. Stir in cauliflower.',
  'Continue stir-frying just until the vegetables are barely softened and the pan is mostly dry, 5 to 7 minutes.',
  'Add the remaining 1 Tbsp. oil, rice, ginger, and garlic powder; stir to coat well.',
  'Cook, stirring, until the mixture is heated through, 3 to 4 minutes.',
  'Push the rice-vegetable mixture to the sides of the pan and pour in eggs, stirring to scramble them until just set, then fold the eggs into the rest of the mixture.',
  'Stir in soy sauce and serve immediately.'],
  "summary": "Pasta with Garlic, Scallions, Cauliflower & Breadcrumbs might be a good recipe to expand your main course repertoire. One portion of this dish contains approximately <b>19g of protein </b>,  <b>20g of fat </b>, and a total of  <b>584 calories </b>. For  <b>$1.63 per serving </b>, this recipe  <b>covers 23% </b> of your daily requirements of vitamins and minerals. This recipe serves 2. It is brought to you by fullbellysisters.blogspot.com. 209 people were glad they tried this recipe. A mixture of scallions, salt and pepper, white wine, and a handful of other ingredients are all it takes to make this recipe so scrumptious. From preparation to the plate, this recipe takes approximately  <b>45 minutes </b>. All things considered, we decided this recipe  <b>deserves a spoonacular score of 83% </b>. This score is awesome. If you like this recipe, take a look at these similar recipes: <a href=\"https://spoonacular.com/recipes/cauliflower-gratin-with-garlic-breadcrumbs-318375\">Cauliflower Gratin with Garlic Breadcrumbs</a>, < href=\"https://spoonacular.com/recipes/pasta-with-cauliflower-sausage-breadcrumbs-30437\">Pasta With Cauliflower, Sausage, & Breadcrumbs</a>, and <a href=\"https://spoonacular.com/recipes/pasta-with-roasted-cauliflower-parsley-and-breadcrumbs-30738\">Pasta With Roasted Cauliflower, Parsley, And Breadcrumbs</a>.",
  "calories": 700,
  "protein": 300,
  "fat": 100,
  "carbs": 300,
  "popularity_score": 17,
  "likes": 25
},
{
  "id": 644387,
  "name": "Garlicky Kale",
  "image": "https://spoonacular.com/recipeImages/644387-312x231.jpg",
  "imageType": "jpg",
        "readyInMinutes": 45,
  "servings": 2,
  "vegan": false,
  "vegetarian": false,
  "dairy_free": false,
  "gluten_free": false,
  "keto": false,
  "low_fodmap": false,
  "ingredients": [
    "2 tablespoons canola oil or vegetable oil, divided",
    "4 scallions, chopped",
    "1 ½ cups frozen peas and carrots",
    "1 (10-oz.) package frozen riced cauliflower",
    "1 cup frozen cooked brown rice",
    "½ teaspoon ground ginger",
    "½ teaspoon garlic powder",
    "2 large eggs, lightly beaten",
    "1 tablespoon reduced-sodium soy sauce"
  ],
  "instructions": ['Heat 1 Tbsp. oil in a large nonstick skillet over medium-high heat.',
  'Add scallions; stir-fry until softened, 3 to 5 minutes.',
  'Add peas and carrots; cook, stirring, for 1 minute. Stir in cauliflower.',
  'Continue stir-frying just until the vegetables are barely softened and the pan is mostly dry, 5 to 7 minutes.',
  'Add the remaining 1 Tbsp. oil, rice, ginger, and garlic powder; stir to coat well.',
  'Cook, stirring, until the mixture is heated through, 3 to 4 minutes.',
  'Push the rice-vegetable mixture to the sides of the pan and pour in eggs, stirring to scramble them until just set, then fold the eggs into the rest of the mixture.',
  'Stir in soy sauce and serve immediately.'],
  "summary": "Pasta with Garlic, Scallions, Cauliflower & Breadcrumbs might be a good recipe to expand your main course repertoire. One portion of this dish contains approximately <b>19g of protein </b>,  <b>20g of fat </b>, and a total of  <b>584 calories </b>. For  <b>$1.63 per serving </b>, this recipe  <b>covers 23% </b> of your daily requirements of vitamins and minerals. This recipe serves 2. It is brought to you by fullbellysisters.blogspot.com. 209 people were glad they tried this recipe. A mixture of scallions, salt and pepper, white wine, and a handful of other ingredients are all it takes to make this recipe so scrumptious. From preparation to the plate, this recipe takes approximately  <b>45 minutes </b>. All things considered, we decided this recipe  <b>deserves a spoonacular score of 83% </b>. This score is awesome. If you like this recipe, take a look at these similar recipes: <a href=\"https://spoonacular.com/recipes/cauliflower-gratin-with-garlic-breadcrumbs-318375\">Cauliflower Gratin with Garlic Breadcrumbs</a>, < href=\"https://spoonacular.com/recipes/pasta-with-cauliflower-sausage-breadcrumbs-30437\">Pasta With Cauliflower, Sausage, & Breadcrumbs</a>, and <a href=\"https://spoonacular.com/recipes/pasta-with-roasted-cauliflower-parsley-and-breadcrumbs-30738\">Pasta With Roasted Cauliflower, Parsley, And Breadcrumbs</a>.",
  "calories": 700,
  "protein": 300,
  "fat": 100,
  "carbs": 300,
  "popularity_score": 17,
  "likes": 25
},
{
  "id": 716268,
  "name": "African Chicken Peanut Stew",
  "image": "https://spoonacular.com/recipeImages/716268-312x231.jpg",
  "imageType": "jpg",
        "readyInMinutes": 45,
  "servings": 2,
  "vegan": false,
  "vegetarian": false,
  "dairy_free": false,
  "gluten_free": false,
  "keto": false,
  "low_fodmap": false,
  "ingredients": [
    "2 tablespoons canola oil or vegetable oil, divided",
    "4 scallions, chopped",
    "1 ½ cups frozen peas and carrots",
    "1 (10-oz.) package frozen riced cauliflower",
    "1 cup frozen cooked brown rice",
    "½ teaspoon ground ginger",
    "½ teaspoon garlic powder",
    "2 large eggs, lightly beaten",
    "1 tablespoon reduced-sodium soy sauce"
  ],
  "instructions": ['Heat 1 Tbsp. oil in a large nonstick skillet over medium-high heat.',
  'Add scallions; stir-fry until softened, 3 to 5 minutes.',
  'Add peas and carrots; cook, stirring, for 1 minute. Stir in cauliflower.',
  'Continue stir-frying just until the vegetables are barely softened and the pan is mostly dry, 5 to 7 minutes.',
  'Add the remaining 1 Tbsp. oil, rice, ginger, and garlic powder; stir to coat well.',
  'Cook, stirring, until the mixture is heated through, 3 to 4 minutes.',
  'Push the rice-vegetable mixture to the sides of the pan and pour in eggs, stirring to scramble them until just set, then fold the eggs into the rest of the mixture.',
  'Stir in soy sauce and serve immediately.'],
  "summary": "Pasta with Garlic, Scallions, Cauliflower & Breadcrumbs might be a good recipe to expand your main course repertoire. One portion of this dish contains approximately <b>19g of protein </b>,  <b>20g of fat </b>, and a total of  <b>584 calories </b>. For  <b>$1.63 per serving </b>, this recipe  <b>covers 23% </b> of your daily requirements of vitamins and minerals. This recipe serves 2. It is brought to you by fullbellysisters.blogspot.com. 209 people were glad they tried this recipe. A mixture of scallions, salt and pepper, white wine, and a handful of other ingredients are all it takes to make this recipe so scrumptious. From preparation to the plate, this recipe takes approximately  <b>45 minutes </b>. All things considered, we decided this recipe  <b>deserves a spoonacular score of 83% </b>. This score is awesome. If you like this recipe, take a look at these similar recipes: <a href=\"https://spoonacular.com/recipes/cauliflower-gratin-with-garlic-breadcrumbs-318375\">Cauliflower Gratin with Garlic Breadcrumbs</a>, < href=\"https://spoonacular.com/recipes/pasta-with-cauliflower-sausage-breadcrumbs-30437\">Pasta With Cauliflower, Sausage, & Breadcrumbs</a>, and <a href=\"https://spoonacular.com/recipes/pasta-with-roasted-cauliflower-parsley-and-breadcrumbs-30738\">Pasta With Roasted Cauliflower, Parsley, And Breadcrumbs</a>.",
  "calories": 700,
  "protein": 300,
  "fat": 100,
  "carbs": 300,
  "popularity_score": 17,
  "likes": 25
},
{
  "id": 716381,
  "name": "Nigerian Snail Stew",
  "image": "https://spoonacular.com/recipeImages/716381-312x231.jpg",
  "imageType": "jpg",
        "readyInMinutes": 45,
  "servings": 2,
  "vegan": false,
  "vegetarian": false,
  "dairy_free": false,
  "gluten_free": false,
  "keto": false,
  "low_fodmap": false,
  "ingredients": [
    "2 tablespoons canola oil or vegetable oil, divided",
    "4 scallions, chopped",
    "1 ½ cups frozen peas and carrots",
    "1 (10-oz.) package frozen riced cauliflower",
    "1 cup frozen cooked brown rice",
    "½ teaspoon ground ginger",
    "½ teaspoon garlic powder",
    "2 large eggs, lightly beaten",
    "1 tablespoon reduced-sodium soy sauce"
  ],
  "instructions": ['Heat 1 Tbsp. oil in a large nonstick skillet over medium-high heat.',
  'Add scallions; stir-fry until softened, 3 to 5 minutes.',
  'Add peas and carrots; cook, stirring, for 1 minute. Stir in cauliflower.',
  'Continue stir-frying just until the vegetables are barely softened and the pan is mostly dry, 5 to 7 minutes.',
  'Add the remaining 1 Tbsp. oil, rice, ginger, and garlic powder; stir to coat well.',
  'Cook, stirring, until the mixture is heated through, 3 to 4 minutes.',
  'Push the rice-vegetable mixture to the sides of the pan and pour in eggs, stirring to scramble them until just set, then fold the eggs into the rest of the mixture.',
  'Stir in soy sauce and serve immediately.'],
  "summary": "Pasta with Garlic, Scallions, Cauliflower & Breadcrumbs might be a good recipe to expand your main course repertoire. One portion of this dish contains approximately <b>19g of protein </b>,  <b>20g of fat </b>, and a total of  <b>584 calories </b>. For  <b>$1.63 per serving </b>, this recipe  <b>covers 23% </b> of your daily requirements of vitamins and minerals. This recipe serves 2. It is brought to you by fullbellysisters.blogspot.com. 209 people were glad they tried this recipe. A mixture of scallions, salt and pepper, white wine, and a handful of other ingredients are all it takes to make this recipe so scrumptious. From preparation to the plate, this recipe takes approximately  <b>45 minutes </b>. All things considered, we decided this recipe  <b>deserves a spoonacular score of 83% </b>. This score is awesome. If you like this recipe, take a look at these similar recipes: <a href=\"https://spoonacular.com/recipes/cauliflower-gratin-with-garlic-breadcrumbs-318375\">Cauliflower Gratin with Garlic Breadcrumbs</a>, < href=\"https://spoonacular.com/recipes/pasta-with-cauliflower-sausage-breadcrumbs-30437\">Pasta With Cauliflower, Sausage, & Breadcrumbs</a>, and <a href=\"https://spoonacular.com/recipes/pasta-with-roasted-cauliflower-parsley-and-breadcrumbs-30738\">Pasta With Roasted Cauliflower, Parsley, And Breadcrumbs</a>.",
  "calories": 700,
  "protein": 300,
  "fat": 100,
  "carbs": 300,
  "popularity_score": 17,
  "likes": 25
},
{
  "id": 782601,
  "name": "Red Kidney Bean Jambalaya",
  "image": "https://spoonacular.com/recipeImages/782601-312x231.jpg",
  "imageType": "jpg",
        "readyInMinutes": 45,
  "servings": 2,
  "vegan": false,
  "vegetarian": false,
  "dairy_free": false,
  "gluten_free": false,
  "keto": false,
  "low_fodmap": false,
  "ingredients": [
    "2 tablespoons canola oil or vegetable oil, divided",
    "4 scallions, chopped",
    "1 ½ cups frozen peas and carrots",
    "1 (10-oz.) package frozen riced cauliflower",
    "1 cup frozen cooked brown rice",
    "½ teaspoon ground ginger",
    "½ teaspoon garlic powder",
    "2 large eggs, lightly beaten",
    "1 tablespoon reduced-sodium soy sauce"
  ],
  "instructions": ['Heat 1 Tbsp. oil in a large nonstick skillet over medium-high heat.',
  'Add scallions; stir-fry until softened, 3 to 5 minutes.',
  'Add peas and carrots; cook, stirring, for 1 minute. Stir in cauliflower.',
  'Continue stir-frying just until the vegetables are barely softened and the pan is mostly dry, 5 to 7 minutes.',
  'Add the remaining 1 Tbsp. oil, rice, ginger, and garlic powder; stir to coat well.',
  'Cook, stirring, until the mixture is heated through, 3 to 4 minutes.',
  'Push the rice-vegetable mixture to the sides of the pan and pour in eggs, stirring to scramble them until just set, then fold the eggs into the rest of the mixture.',
  'Stir in soy sauce and serve immediately.'],
  "summary": "Pasta with Garlic, Scallions, Cauliflower & Breadcrumbs might be a good recipe to expand your main course repertoire. One portion of this dish contains approximately <b>19g of protein </b>,  <b>20g of fat </b>, and a total of  <b>584 calories </b>. For  <b>$1.63 per serving </b>, this recipe  <b>covers 23% </b> of your daily requirements of vitamins and minerals. This recipe serves 2. It is brought to you by fullbellysisters.blogspot.com. 209 people were glad they tried this recipe. A mixture of scallions, salt and pepper, white wine, and a handful of other ingredients are all it takes to make this recipe so scrumptious. From preparation to the plate, this recipe takes approximately  <b>45 minutes </b>. All things considered, we decided this recipe  <b>deserves a spoonacular score of 83% </b>. This score is awesome. If you like this recipe, take a look at these similar recipes: <a href=\"https://spoonacular.com/recipes/cauliflower-gratin-with-garlic-breadcrumbs-318375\">Cauliflower Gratin with Garlic Breadcrumbs</a>, < href=\"https://spoonacular.com/recipes/pasta-with-cauliflower-sausage-breadcrumbs-30437\">Pasta With Cauliflower, Sausage, & Breadcrumbs</a>, and <a href=\"https://spoonacular.com/recipes/pasta-with-roasted-cauliflower-parsley-and-breadcrumbs-30738\">Pasta With Roasted Cauliflower, Parsley, And Breadcrumbs</a>.",
  "calories": 700,
  "protein": 300,
  "fat": 100,
  "carbs": 300,
  "popularity_score": 17,
  "likes": 25
},
{
  "id": 794349,
  "name": "Broccoli and Chickpea Rice Salad",
  "image": "https://spoonacular.com/recipeImages/794349-312x231.jpg",
  "imageType": "jpg",
        "readyInMinutes": 45,
  "servings": 2,
  "vegan": false,
  "vegetarian": false,
  "dairy_free": false,
  "gluten_free": false,
  "keto": false,
  "low_fodmap": false,
  "ingredients": [
    "2 tablespoons canola oil or vegetable oil, divided",
    "4 scallions, chopped",
    "1 ½ cups frozen peas and carrots",
    "1 (10-oz.) package frozen riced cauliflower",
    "1 cup frozen cooked brown rice",
    "½ teaspoon ground ginger",
    "½ teaspoon garlic powder",
    "2 large eggs, lightly beaten",
    "1 tablespoon reduced-sodium soy sauce"
  ],
  "instructions": ['Heat 1 Tbsp. oil in a large nonstick skillet over medium-high heat.',
  'Add scallions; stir-fry until softened, 3 to 5 minutes.',
  'Add peas and carrots; cook, stirring, for 1 minute. Stir in cauliflower.',
  'Continue stir-frying just until the vegetables are barely softened and the pan is mostly dry, 5 to 7 minutes.',
  'Add the remaining 1 Tbsp. oil, rice, ginger, and garlic powder; stir to coat well.',
  'Cook, stirring, until the mixture is heated through, 3 to 4 minutes.',
  'Push the rice-vegetable mixture to the sides of the pan and pour in eggs, stirring to scramble them until just set, then fold the eggs into the rest of the mixture.',
  'Stir in soy sauce and serve immediately.'],
  "summary": "Pasta with Garlic, Scallions, Cauliflower & Breadcrumbs might be a good recipe to expand your main course repertoire. One portion of this dish contains approximately <b>19g of protein </b>,  <b>20g of fat </b>, and a total of  <b>584 calories </b>. For  <b>$1.63 per serving </b>, this recipe  <b>covers 23% </b> of your daily requirements of vitamins and minerals. This recipe serves 2. It is brought to you by fullbellysisters.blogspot.com. 209 people were glad they tried this recipe. A mixture of scallions, salt and pepper, white wine, and a handful of other ingredients are all it takes to make this recipe so scrumptious. From preparation to the plate, this recipe takes approximately  <b>45 minutes </b>. All things considered, we decided this recipe  <b>deserves a spoonacular score of 83% </b>. This score is awesome. If you like this recipe, take a look at these similar recipes: <a href=\"https://spoonacular.com/recipes/cauliflower-gratin-with-garlic-breadcrumbs-318375\">Cauliflower Gratin with Garlic Breadcrumbs</a>, < href=\"https://spoonacular.com/recipes/pasta-with-cauliflower-sausage-breadcrumbs-30437\">Pasta With Cauliflower, Sausage, & Breadcrumbs</a>, and <a href=\"https://spoonacular.com/recipes/pasta-with-roasted-cauliflower-parsley-and-breadcrumbs-30738\">Pasta With Roasted Cauliflower, Parsley, And Breadcrumbs</a>.",
  "calories": 700,
  "protein": 300,
  "fat": 100,
  "carbs": 300,
  "popularity_score": 17,
  "likes": 25
},
{
  "id": 715446,
  "name": "Slow Cooker Beef Stew",
  "image": "https://spoonacular.com/recipeImages/715446-312x231.jpg",
  "imageType": "jpg",
        "readyInMinutes": 45,
  "servings": 2,
  "vegan": false,
  "vegetarian": false,
  "dairy_free": false,
  "gluten_free": false,
  "keto": false,
  "low_fodmap": false,
  "ingredients": [
    "2 tablespoons canola oil or vegetable oil, divided",
    "4 scallions, chopped",
    "1 ½ cups frozen peas and carrots",
    "1 (10-oz.) package frozen riced cauliflower",
    "1 cup frozen cooked brown rice",
    "½ teaspoon ground ginger",
    "½ teaspoon garlic powder",
    "2 large eggs, lightly beaten",
    "1 tablespoon reduced-sodium soy sauce"
  ],
  "instructions": ['Heat 1 Tbsp. oil in a large nonstick skillet over medium-high heat.',
  'Add scallions; stir-fry until softened, 3 to 5 minutes.',
  'Add peas and carrots; cook, stirring, for 1 minute. Stir in cauliflower.',
  'Continue stir-frying just until the vegetables are barely softened and the pan is mostly dry, 5 to 7 minutes.',
  'Add the remaining 1 Tbsp. oil, rice, ginger, and garlic powder; stir to coat well.',
  'Cook, stirring, until the mixture is heated through, 3 to 4 minutes.',
  'Push the rice-vegetable mixture to the sides of the pan and pour in eggs, stirring to scramble them until just set, then fold the eggs into the rest of the mixture.',
  'Stir in soy sauce and serve immediately.'],
  "summary": "Pasta with Garlic, Scallions, Cauliflower & Breadcrumbs might be a good recipe to expand your main course repertoire. One portion of this dish contains approximately <b>19g of protein </b>,  <b>20g of fat </b>, and a total of  <b>584 calories </b>. For  <b>$1.63 per serving </b>, this recipe  <b>covers 23% </b> of your daily requirements of vitamins and minerals. This recipe serves 2. It is brought to you by fullbellysisters.blogspot.com. 209 people were glad they tried this recipe. A mixture of scallions, salt and pepper, white wine, and a handful of other ingredients are all it takes to make this recipe so scrumptious. From preparation to the plate, this recipe takes approximately  <b>45 minutes </b>. All things considered, we decided this recipe  <b>deserves a spoonacular score of 83% </b>. This score is awesome. If you like this recipe, take a look at these similar recipes: <a href=\"https://spoonacular.com/recipes/cauliflower-gratin-with-garlic-breadcrumbs-318375\">Cauliflower Gratin with Garlic Breadcrumbs</a>, < href=\"https://spoonacular.com/recipes/pasta-with-cauliflower-sausage-breadcrumbs-30437\">Pasta With Cauliflower, Sausage, & Breadcrumbs</a>, and <a href=\"https://spoonacular.com/recipes/pasta-with-roasted-cauliflower-parsley-and-breadcrumbs-30738\">Pasta With Roasted Cauliflower, Parsley, And Breadcrumbs</a>.",
  "calories": 700,
  "protein": 300,
  "fat": 100,
  "carbs": 300,
  "popularity_score": 17,
  "likes": 25
},
{
  "id": 715415,
  "name": "Red Lentil Soup with Chicken and Turnips",
  "image": "https://spoonacular.com/recipeImages/715415-312x231.jpg",
  "imageType": "jpg",
        "readyInMinutes": 45,
  "servings": 2,
  "vegan": false,
  "vegetarian": false,
  "dairy_free": false,
  "gluten_free": false,
  "keto": false,
  "low_fodmap": false,
  "ingredients": [
    "2 tablespoons canola oil or vegetable oil, divided",
    "4 scallions, chopped",
    "1 ½ cups frozen peas and carrots",
    "1 (10-oz.) package frozen riced cauliflower",
    "1 cup frozen cooked brown rice",
    "½ teaspoon ground ginger",
    "½ teaspoon garlic powder",
    "2 large eggs, lightly beaten",
    "1 tablespoon reduced-sodium soy sauce"
  ],
  "instructions": ['Heat 1 Tbsp. oil in a large nonstick skillet over medium-high heat.',
  'Add scallions; stir-fry until softened, 3 to 5 minutes.',
  'Add peas and carrots; cook, stirring, for 1 minute. Stir in cauliflower.',
  'Continue stir-frying just until the vegetables are barely softened and the pan is mostly dry, 5 to 7 minutes.',
  'Add the remaining 1 Tbsp. oil, rice, ginger, and garlic powder; stir to coat well.',
  'Cook, stirring, until the mixture is heated through, 3 to 4 minutes.',
  'Push the rice-vegetable mixture to the sides of the pan and pour in eggs, stirring to scramble them until just set, then fold the eggs into the rest of the mixture.',
  'Stir in soy sauce and serve immediately.'],
  "summary": "Pasta with Garlic, Scallions, Cauliflower & Breadcrumbs might be a good recipe to expand your main course repertoire. One portion of this dish contains approximately <b>19g of protein </b>,  <b>20g of fat </b>, and a total of  <b>584 calories </b>. For  <b>$1.63 per serving </b>, this recipe  <b>covers 23% </b> of your daily requirements of vitamins and minerals. This recipe serves 2. It is brought to you by fullbellysisters.blogspot.com. 209 people were glad they tried this recipe. A mixture of scallions, salt and pepper, white wine, and a handful of other ingredients are all it takes to make this recipe so scrumptious. From preparation to the plate, this recipe takes approximately  <b>45 minutes </b>. All things considered, we decided this recipe  <b>deserves a spoonacular score of 83% </b>. This score is awesome. If you like this recipe, take a look at these similar recipes: <a href=\"https://spoonacular.com/recipes/cauliflower-gratin-with-garlic-breadcrumbs-318375\">Cauliflower Gratin with Garlic Breadcrumbs</a>, < href=\"https://spoonacular.com/recipes/pasta-with-cauliflower-sausage-breadcrumbs-30437\">Pasta With Cauliflower, Sausage, & Breadcrumbs</a>, and <a href=\"https://spoonacular.com/recipes/pasta-with-roasted-cauliflower-parsley-and-breadcrumbs-30738\">Pasta With Roasted Cauliflower, Parsley, And Breadcrumbs</a>.",
  "calories": 700,
  "protein": 300,
  "fat": 100,
  "carbs": 300,
  "popularity_score": 17,
  "likes": 25
}
]

module.exports = recipe